### ISSUE TITLE
I can not get it to successfully output a wav file - issue at line 119

### ISSUE THREAD

**Issue by bdorr1105** [solusipse/spectrology#5]
**The command I ran**

sudo python /opt/spectrology/spectrology.py secret-text.bmp -b 16000 -t 25000 -p 120  
Input file: secret-text.bmp.
Frequency range: 16000 - 25000.
Pixels per second: 120.
Sampling rate: 44100.
Rotate Image: no.

**the error:**

Traceback (most recent call last):
  File "/opt/spectrology/spectrology.py", line 119, in <module>
    convert(*inpt)
  File "/opt/spectrology/spectrology.py", line 101, in convert
    output.writeframes(data.tostring())
AttributeError: 'array.array' object has no attribute 'tostring'

**Comment by arkelops** [comment]
Simply removing the `.tostring()` in line 102 will do the trick
